### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by adibas03**
Code clean up by Panos @h3ph4est7s

### CODE REVIEW

**Comment by adibas03** [comment]
Closing to allow completion of work on the develop branch by @h3ph4est7s. Will be re-opened once ready

**Comment by adibas03** [comment]
Updates by @h3ph4est7s  and @PreciousTosin  ready for review

**Comment by adibas03** [comment]
@h3ph4est7s 
https://github.com/Superdao-DAO/Superdao-webclaim/blob/develop/package.json#L17
https://github.com/Superdao-DAO/Superdao-webclaim/blob/develop/README.md
should be 'superdao'

**Review by adibas03 — COMMENTED** [review]
Thanks @h3ph4est7s

**Review by coderwithattitude — CHANGES_REQUESTED** [review]
issue resolved

**Review by coderwithattitude — APPROVED** [review]

**Comment by innovator256** [comment]
Merging based on coders review for time sake

**Pull request closed without merging**
